# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "app"

rule_files:

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "web"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]
