"""init

Revision ID: 4302c77fade3
Revises: 
Create Date: 2023-07-02 16:35:35.155969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4302c77fade3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('mailing_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tag_filter', sa.String(), nullable=True),
    sa.Column('mobile_code_filter', sa.String(), nullable=True),
    sa.CheckConstraint('(tag_filter IS NOT NULL OR mobile_code_filter IS NOT NULL)', name='one_filter_is_not_null'),
    sa.CheckConstraint('start_datetime <= end_datetime', name='check_start_end_datetime'),
    sa.PrimaryKeyConstraint('mailing_id')
    )
    op.create_table('recipients',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('mobile_code', sa.String(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('recipient_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sending_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='messagestatus'), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('mailing_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.mailing_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.recipient_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('recipients')
    op.drop_table('mailings')
    # ### end Alembic commands ###
