"""mailing constr

Revision ID: 661af4176d35
Revises: fca683288354
Create Date: 2023-06-28 22:45:08.513321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661af4176d35'
down_revision = 'fca683288354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
