"""mailing model

Revision ID: a9272aed2a91
Revises: 
Create Date: 2023-06-26 23:22:21.609844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9272aed2a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('mailing_id', sa.UUID(), nullable=False),
    sa.Column('mailing_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tag_filter', sa.String(), nullable=True),
    sa.Column('mobile_code_filter', sa.String(), nullable=True),
    sa.CheckConstraint('(tag_filter IS NOT NULL OR mobile_code_filter IS NOT NULL)', name='one_filter_is_not_null'),
    sa.PrimaryKeyConstraint('mailing_id')
    )
    op.create_table('recipients',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('mobile_code', sa.String(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('recipient_id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipients')
    op.drop_table('mailings')
    # ### end Alembic commands ###
